export type BlogBlockType = "h2" | "h3" | "paragraph" | "list";

export interface ParsedBlock {
  type: BlogBlockType;
  text: string;
  items: string[];
}

export interface ParsedArticle {
  title: string;
  slug: string;
  excerpt: string;
  category: string;
  blocks: ParsedBlock[];
  faqs: { a: string; b: string }[];
}

/**
 * Clean inline formatting: decode entities, format bold, italic, code, links.
 */
export function cleanInlineText(str: string): string {
  if (!str) return "";
  let out = str
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&rsquo;/g, "'")
    .replace(/&lsquo;/g, "'")
    .replace(/&ldquo;/g, '"')
    .replace(/&rdquo;/g, '"')
    .replace(/&ndash;/g, "–")
    .replace(/&mdash;/g, "—")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/\r\n/g, "\n")
    .replace(/\r/g, "\n");

  out = out.replace(/[ \t]+/g, " ").trim();
  return out;
}

export function slugify(str: string): string {
  return str
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-");
}

/**
 * Convert a DOM element to markdown-style inline string.
 */
function domToMarkdownInline(node: Node): string {
  if (node.nodeType === Node.TEXT_NODE) {
    return node.textContent || "";
  }

  if (node.nodeType !== Node.ELEMENT_NODE) {
    return "";
  }

  const el = node as HTMLElement;
  const tag = el.tagName.toLowerCase();

  let inner = "";
  el.childNodes.forEach((child) => {
    inner += domToMarkdownInline(child);
  });

  if (!inner && tag !== "br") return "";

  switch (tag) {
    case "a": {
      const href = el.getAttribute("href");
      if (href && href !== "#" && !href.startsWith("javascript:")) {
        return `[${cleanInlineText(inner)}](${href})`;
      }
      return inner;
    }
    case "strong":
    case "b":
      return `**${inner.trim()}**`;
    case "em":
    case "i":
      return `*${inner.trim()}*`;
    case "code":
      return `\`${inner.trim()}\``;
    case "br":
      return "\n";
    default:
      return inner;
  }
}

/**
 * Convert an HTML table element to a Markdown table string.
 */
function tableToMarkdown(tableEl: HTMLElement): string {
  const rows: string[][] = [];
  const trs = tableEl.querySelectorAll("tr");
  trs.forEach((tr) => {
    const cells: string[] = [];
    tr.querySelectorAll("th, td").forEach((cell) => {
      cells.push(cleanInlineText(cell.textContent || "").replace(/\|/g, "\\|"));
    });
    if (cells.length > 0) rows.push(cells);
  });

  if (rows.length === 0) return "";

  const colCount = Math.max(...rows.map((r) => r.length));
  const padRow = (r: string[]) => {
    while (r.length < colCount) r.push("");
    return `| ${r.join(" | ")} |`;
  };

  const mdRows: string[] = [];
  mdRows.push(padRow(rows[0]));
  mdRows.push(`| ${Array(colCount).fill("---").join(" | ")} |`);

  for (let i = 1; i < rows.length; i++) {
    mdRows.push(padRow(rows[i]));
  }

  return mdRows.join("\n");
}

export function hasHtmlTags(text: string): boolean {
  return /<\/?(h[1-6]|p|ul|ol|li|div|blockquote|section|article|span|strong|table)[^>]*>/i.test(text);
}

/**
 * Standard known headings used in AI content creators like Scalenut, ChatGPT, SurferSEO
 */
const KNOWN_HEADINGS: Record<string, "h2" | "h3"> = {
  "key highlights": "h2",
  "key takeaways": "h2",
  "introduction": "h2",
  "overview": "h2",
  "conclusion": "h2",
  "summary": "h2",
  "final thoughts": "h2",
  "table of contents": "h2",
  "frequently asked questions": "h2",
  "frequently asked questions (faq)": "h2",
  "faqs": "h2",
  "faq": "h2",
};

/**
 * Check if a text line is a heading:
 * Handles Markdown (##, ###), Prefixes (H2:, H3:), Bold (**Title**), Numbering (1. Title),
 * and Plain-Text Title Case section headings generated by Scalenut.
 */
export function isLikelyHeading(text: string): { isHeading: boolean; level: "h2" | "h3"; cleanText: string } {
  const t = text.trim();
  if (!t) return { isHeading: false, level: "h2", cleanText: "" };

  // 1. Markdown hashes
  if (/^##\s+/.test(t)) {
    return { isHeading: true, level: "h2", cleanText: t.replace(/^##\s+/, "").trim() };
  }
  if (/^###\s+/.test(t) || /^####\s+/.test(t) || /^#\s+/.test(t)) {
    return { isHeading: true, level: "h3", cleanText: t.replace(/^#+\s+/, "").trim() };
  }

  // 2. Explicit prefixes: H2:, h2:, [H2], Heading 2:
  const h2Prefix = /^(h2\s*[:\-–—]|\[h2\]|heading\s*2\s*[:\-–—])\s*/i;
  if (h2Prefix.test(t)) {
    return { isHeading: true, level: "h2", cleanText: t.replace(h2Prefix, "").trim() };
  }

  const h3Prefix = /^(h3\s*[:\-–—]|\[h3\]|heading\s*3\s*[:\-–—])\s*/i;
  if (h3Prefix.test(t)) {
    return { isHeading: true, level: "h3", cleanText: t.replace(h3Prefix, "").trim() };
  }

  // 3. Known standard headings
  const lower = t.toLowerCase();
  if (KNOWN_HEADINGS[lower]) {
    return { isHeading: true, level: KNOWN_HEADINGS[lower], cleanText: t };
  }

  // 4. Bold line: **Heading**
  const boldMatch = t.match(/^\*\*(.+)\*\*$/);
  if (boldMatch && boldMatch[1]) {
    const inner = boldMatch[1].trim();
    if (inner.length <= 110 && !inner.endsWith(".")) {
      const isSub = /^[0-9]+\.[0-9]+/.test(inner) || inner.includes(":");
      return { isHeading: true, level: isSub ? "h3" : "h2", cleanText: inner };
    }
  }

  // 5. Numbered headings: "1. Introduction" or "1.1 Subsection"
  const numberedH2 = t.match(/^([0-9]+)\.\s+([A-Z][^.\n]{3,110})$/);
  if (numberedH2 && !numberedH2[2].endsWith(".")) {
    return { isHeading: true, level: "h2", cleanText: t };
  }
  const numberedH3 = t.match(/^([0-9]+\.[0-9]+)\s+([A-Z][^.\n]{3,110})$/);
  if (numberedH3 && !numberedH3[2].endsWith(".")) {
    return { isHeading: true, level: "h3", cleanText: t };
  }

  // 6. Plain Text Title Case headings from Scalenut
  // Characteristics:
  // - Length between 4 and 100 characters
  // - Starts with an uppercase letter
  // - Does NOT end with terminal punctuation (. or , or ;)
  // - High ratio of capitalized words
  // - Can end with ? or :
  if (t.length >= 4 && t.length <= 100 && /^[A-Z0-9]/.test(t) && !t.endsWith(".") && !t.endsWith(",") && !t.endsWith(";")) {
    const words = t.split(/\s+/).filter(Boolean);
    if (words.length >= 1 && words.length <= 16) {
      // Calculate capitalization ratio
      const capWords = words.filter((w) => /^[A-Z0-9]/.test(w)).length;
      const capRatio = capWords / words.length;

      // Small words that are normally lowercase in title case
      const commonMinorWords = new Set(["in", "for", "the", "a", "an", "and", "or", "of", "to", "with", "vs", "on", "at", "by", "from", "as", "is"]);
      const significantWords = words.filter((w) => !commonMinorWords.has(w.toLowerCase()));
      const sigCapWords = significantWords.filter((w) => /^[A-Z0-9]/.test(w)).length;
      const sigCapRatio = significantWords.length > 0 ? sigCapWords / significantWords.length : capRatio;

      if (sigCapRatio >= 0.7 || capRatio >= 0.5 || t.includes(":") || t.endsWith("?")) {
        // Decide H2 vs H3: subtopics with colons or questions are often H3
        const isSub = t.includes(":") || (t.endsWith("?") && words.length <= 12) || words.length <= 3;
        return { isHeading: true, level: isSub ? "h3" : "h2", cleanText: t };
      }
    }
  }

  return { isHeading: false, level: "h2", cleanText: t };
}

/**
 * Parses rich HTML (from clipboard or source) into structured blocks.
 */
export function parseHtmlToBlocks(html: string): ParsedBlock[] {
  if (typeof window === "undefined") {
    return parseTextToBlocks(html);
  }

  const parser = new DOMParser();
  const doc = parser.parseFromString(html, "text/html");

  const badTags = doc.querySelectorAll("script, style, meta, noscript, link");
  badTags.forEach((el) => el.remove());

  const blocks: ParsedBlock[] = [];

  function processElement(el: HTMLElement) {
    const tag = el.tagName.toLowerCase();

    if (tag === "h1" || tag === "h2") {
      const text = cleanInlineText(domToMarkdownInline(el).replace(/^#+\s*/, ""));
      if (text) {
        blocks.push({ type: "h2", text, items: [] });
      }
      return;
    }

    if (tag === "h3" || tag === "h4" || tag === "h5" || tag === "h6") {
      const text = cleanInlineText(domToMarkdownInline(el).replace(/^#+\s*/, ""));
      if (text) {
        blocks.push({ type: "h3", text, items: [] });
      }
      return;
    }

    if (tag === "table") {
      const mdTable = tableToMarkdown(el);
      if (mdTable) {
        blocks.push({ type: "paragraph", text: mdTable, items: [] });
      }
      return;
    }

    if (tag === "ul" || tag === "ol") {
      const lis = el.querySelectorAll(":scope > li");
      const items: string[] = [];
      lis.forEach((li) => {
        const itemText = cleanInlineText(domToMarkdownInline(li));
        if (itemText) items.push(itemText);
      });
      if (items.length > 0) {
        blocks.push({ type: "list", text: "", items });
      }
      return;
    }

    if (tag === "p" || tag === "blockquote") {
      const text = cleanInlineText(domToMarkdownInline(el));
      if (!text) return;

      const headingCheck = isLikelyHeading(text);
      if (headingCheck.isHeading) {
        blocks.push({ type: headingCheck.level, text: headingCheck.cleanText, items: [] });
      } else {
        blocks.push({ type: "paragraph", text, items: [] });
      }
      return;
    }

    const hasBlockChildren = el.querySelector("h1, h2, h3, h4, h5, h6, p, ul, ol, blockquote, div, section, table");
    if (hasBlockChildren) {
      Array.from(el.children).forEach((child) => {
        processElement(child as HTMLElement);
      });
    } else {
      const text = cleanInlineText(domToMarkdownInline(el));
      if (text) {
        const headingCheck = isLikelyHeading(text);
        if (headingCheck.isHeading) {
          blocks.push({ type: headingCheck.level, text: headingCheck.cleanText, items: [] });
        } else {
          blocks.push({ type: "paragraph", text, items: [] });
        }
      }
    }
  }

  Array.from(doc.body.children).forEach((child) => {
    processElement(child as HTMLElement);
  });

  return blocks;
}

/**
 * Parses markdown or plain text (with bullets, numbered headers, bold titles, Scalenut format).
 */
export function parseTextToBlocks(rawText: string): ParsedBlock[] {
  const parsed = parseFullArticle(rawText);
  return parsed.blocks;
}

/**
 * Comprehensive Smart Parser for Scalenut, ChatGPT, Claude, and Google Docs articles.
 * Extracts Title, Slug, Excerpt, Content Blocks (H2/H3/Lists/Paragraphs), and FAQs.
 */
export function parseFullArticle(rawText: string, htmlInput?: string): ParsedArticle {
  if (!rawText.trim() && !htmlInput?.trim()) {
    return { title: "", slug: "", excerpt: "", category: "Web Development", blocks: [], faqs: [] };
  }

  // If rich HTML is available with HTML tags
  if (htmlInput && htmlInput.trim() && hasHtmlTags(htmlInput)) {
    const htmlBlocks = parseHtmlToBlocks(htmlInput);
    if (htmlBlocks.length > 0) {
      return buildArticleFromBlocks(htmlBlocks);
    }
  }

  const lines = rawText.split(/\r?\n/).map((l) => l.trim());
  while (lines.length > 0 && !lines[0]) lines.shift();

  let title = "";
  // Check if first non-empty line is an Article Title
  if (lines.length > 0) {
    const first = lines[0];
    if (first.length <= 150 && !first.endsWith(".")) {
      title = first.replace(/^#+\s*/, "").replace(/^title:\s*/i, "").trim();
      lines.shift();
    }
  }

  // Group remaining lines into raw blank-line separated chunks
  const chunks: string[][] = [];
  let currentChunk: string[] = [];

  for (const line of lines) {
    if (!line) {
      if (currentChunk.length > 0) {
        chunks.push(currentChunk);
        currentChunk = [];
      }
    } else {
      currentChunk.push(line);
    }
  }
  if (currentChunk.length > 0) chunks.push(currentChunk);

  const blocks: ParsedBlock[] = [];
  const faqs: { a: string; b: string }[] = [];

  let inFaqSection = false;
  let currentFaqQ = "";
  let currentFaqAns: string[] = [];

  const flushFaq = () => {
    if (currentFaqQ && currentFaqAns.length > 0) {
      faqs.push({
        a: currentFaqQ,
        b: currentFaqAns.join(" ").trim(),
      });
      currentFaqQ = "";
      currentFaqAns = [];
    }
  };

  for (let i = 0; i < chunks.length; i++) {
    const chunk = chunks[i];
    const textJoined = chunk.join(" ").trim();
    const firstLine = chunk[0];

    // Check if FAQ section start
    if (/^frequently asked questions/i.test(firstLine) || /^faqs?$/i.test(firstLine)) {
      inFaqSection = true;
      blocks.push({ type: "h2", text: firstLine, items: [] });
      continue;
    }

    if (inFaqSection) {
      // Exit FAQ on Conclusion or Summary
      if (/^conclusion$/i.test(firstLine) || /^summary$/i.test(firstLine) || /^final thoughts$/i.test(firstLine)) {
        flushFaq();
        inFaqSection = false;
        blocks.push({ type: "h2", text: firstLine, items: [] });
        continue;
      }

      // Check if chunk is a Question
      const isQuestion = firstLine.endsWith("?") || (chunk.length === 1 && firstLine.length <= 120 && !firstLine.endsWith("."));
      if (isQuestion) {
        flushFaq();
        currentFaqQ = firstLine;
        continue;
      } else if (currentFaqQ) {
        currentFaqAns.push(textJoined);
        continue;
      }
    }

    // Check if single line is a Heading
    if (chunk.length === 1) {
      const headingCheck = isLikelyHeading(firstLine);
      if (headingCheck.isHeading) {
        blocks.push({
          type: headingCheck.level,
          text: headingCheck.cleanText,
          items: [],
        });
        continue;
      }
    }

    // Check for bullet list items
    const isBulletList = chunk.every((l) => /^[•◦▪▫\-\*\+–—✓✔]|\d+[\.\)]/.test(l));
    if (isBulletList) {
      blocks.push({
        type: "list",
        text: "",
        items: chunk.map((l) => l.replace(/^[•◦▪▫\-\*\+–—✓✔\d\.\)]+\s*/, "").trim()),
      });
      continue;
    }

    // Scalenut Key Highlights or Takeaways list:
    // When the previous block was "Key Highlights", "What They Offer", etc., and each chunk is 1 sentence
    const prevBlock = blocks[blocks.length - 1];
    const isUnderHighlights = prevBlock && (prevBlock.text === "Key Highlights" || /what they offer/i.test(prevBlock.text));
    if (isUnderHighlights && chunk.length === 1 && firstLine.length <= 180 && !firstLine.includes("\n")) {
      // Group with previous list if exists, otherwise create new list
      if (prevBlock.type === "list") {
        prevBlock.items.push(firstLine);
        continue;
      } else if (blocks.length > 0 && blocks[blocks.length - 1].type !== "list") {
        // Peek ahead: are subsequent chunks also highlight sentences?
        const nextChunk = chunks[i + 1];
        if (nextChunk && nextChunk.length === 1 && nextChunk[0].length <= 180 && !isLikelyHeading(nextChunk[0]).isHeading) {
          blocks.push({
            type: "list",
            text: "",
            items: [firstLine],
          });
          continue;
        }
      }
    }

    // If current block is a table in plain text (pipe delimited or markdown table)
    if (chunk.some((l) => l.includes("|"))) {
      blocks.push({
        type: "paragraph",
        text: chunk.join("\n"),
        items: [],
      });
      continue;
    }

    // Regular Paragraph
    blocks.push({
      type: "paragraph",
      text: textJoined,
      items: [],
    });
  }

  flushFaq();

  // If no title was found at the beginning, grab the first H2
  if (!title) {
    const firstH2 = blocks.find((b) => b.type === "h2");
    if (firstH2) title = firstH2.text;
  }

  const slug = slugify(title);

  // Extract Excerpt: first substantial paragraph after Introduction or first paragraph
  let excerpt = "";
  const firstP = blocks.find((b) => b.type === "paragraph" && b.text.length > 60 && !b.text.includes("|"));
  if (firstP) {
    excerpt = firstP.text.length > 280 ? firstP.text.slice(0, 277) + "..." : firstP.text;
  }

  // Detect category from title keywords
  let category = "Web Development";
  const titleLower = title.toLowerCase();
  if (titleLower.includes("seo") || titleLower.includes("rank") || titleLower.includes("traffic")) {
    category = "SEO";
  } else if (titleLower.includes("server") || titleLower.includes("cloud") || titleLower.includes("hosting") || titleLower.includes("devops") || titleLower.includes("security")) {
    category = "Infrastructure";
  } else if (titleLower.includes("ecommerce") || titleLower.includes("shop") || titleLower.includes("store")) {
    category = "E-Commerce";
  } else if (titleLower.includes("lead") || titleLower.includes("ads") || titleLower.includes("marketing")) {
    category = "Marketing";
  }

  return {
    title,
    slug,
    excerpt,
    category,
    blocks,
    faqs,
  };
}

function buildArticleFromBlocks(blocks: ParsedBlock[]): ParsedArticle {
  let title = "";
  const firstH2 = blocks.find((b) => b.type === "h2");
  if (firstH2) title = firstH2.text;

  const slug = slugify(title);

  let excerpt = "";
  const firstP = blocks.find((b) => b.type === "paragraph" && b.text.length > 60);
  if (firstP) {
    excerpt = firstP.text.length > 280 ? firstP.text.slice(0, 277) + "..." : firstP.text;
  }

  return {
    title,
    slug,
    excerpt,
    category: "Web Development",
    blocks,
    faqs: [],
  };
}

/**
 * Universal parse function used by BlockEditor and BlogForm.
 */
export function parseArticleContent(textInput: string, htmlInput?: string): ParsedBlock[] {
  const result = parseFullArticle(textInput, htmlInput);
  return result.blocks;
}
