-- ====================================================================
-- GGM Technologies: Complete Master Restore (685 Locations + All Mappings)
-- Restores all URLs discovered by Google Search Console
-- ====================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- 1. Insert/Update all 221 Brand New Locations
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_1', 'abu-dhabi', 'Abu Dhabi', 'United Arab Emirates', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_2', 'akola', 'Akola', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_3', 'amravati', 'Amravati', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_4', 'andheri', 'Andheri', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_5', 'bandra', 'Bandra', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_6', 'bellandur', 'Bellandur', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_7', 'bengaluru', 'Bengaluru', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_8', 'bettahalasuru', 'Bettahalasuru', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_9', 'bhandara', 'Bhandara', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_10', 'bhayandar', 'Bhayandar', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_11', 'borivali', 'Borivali', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_12', 'btm-layout', 'BTM Layout', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_13', 'bur-dubai', 'Bur Dubai', 'United Arab Emirates', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_14', 'cbd-belapur', 'CBD Belapur', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_15', 'chhatrapati-sambhaji-nagar', 'Chhatrapati Sambhaji Nagar', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_16', 'chhatrapati-shivaji-maharaj-terminus', 'Chhatrapati Shivaji Maharaj Terminus (CSMT)', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_17', 'chickpete', 'Chickpete', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_18', 'chunabhatti', 'Chunabhatti', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_19', 'churchgate', 'Churchgate', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_20', 'cubbon-park', 'Cubbon Park', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_21', 'deepanjali-nagar', 'Deepanjali Nagar', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_22', 'deira', 'Deira', 'United Arab Emirates', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_23', 'devarabeesanahalli', 'Devarabeesanahalli', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_24', 'dhule', 'Dhule', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_25', 'dockyard-road', 'Dockyard Road', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_26', 'doddajala', 'Doddajala', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_27', 'doddakallasandra', 'Doddakallasandra', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_28', 'esic', 'ESIC Hospital', 'India', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_29', 'fujairah', 'Fujairah', 'United Arab Emirates', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_30', 'gadchiroli', 'Gadchiroli', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_31', 'goraguntepalya', 'Goraguntepalya', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_32', 'grant-road', 'Grant Road', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_33', 'hadapsar', 'Hadapsar', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_34', 'hebbagodi', 'Hebbagodi', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_35', 'hongasandra', 'Hongasandra', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_36', 'hoodi', 'Hoodi', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_37', 'hope-farm-circle', 'Hope Farm Circle', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_38', 'hosahalli-nelamangala', 'Hosahalli Nelamangala', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_39', 'huskur', 'Huskur', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_40', 'hutatma-chowk-mumbai', 'Hutatma Chowk Mumbai', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_41', 'ic-colony', 'Ic Colony', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_42', 'iit-bombay', 'IIT Bombay', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_43', 'jayanagar', 'Jayanagar', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_44', 'jogeshwari', 'Jogeshwari', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_45', 'kadugodi', 'Kadugodi', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_46', 'kalyani-nagar', 'Kalyani Nagar', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_47', 'khandeshwar', 'Khandeshwar', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_48', 'khar-road', 'Khar Road', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_49', 'kings-circle', 'Kings Circle', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_50', 'konanakunte', 'Konanakunte', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_51', 'koregaonpark', 'Koregaonpark', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_52', 'kudlu-gate', 'Kudlu Gate', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_53', 'lalbagh-road', 'Lalbagh Road', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_54', 'madavara', 'Madavara', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_55', 'madinat-al-maktoum', 'Madinat Al Maktoum', 'United Arab Emirates', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_56', 'madinat-al-qudra', 'Madinat Al Qudra', 'United Arab Emirates', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_57', 'mahavir-nagar', 'Mahavir Nagar', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_58', 'mandala-mankhurd', 'Mandala Mankhurd', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_59', 'manjunatha-nagar', 'Manjunatha Nagar', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_60', 'mansarovar', 'Mansarovar', 'India', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_61', 'mulund', 'Mulund', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_62', 'mumbai-central', 'Mumbai Central', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_63', 'mumbai-city', 'Mumbai City', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_64', 'mushrif', 'Mushrif', 'United Arab Emirates', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_65', 'mysore-road', 'Mysore Road', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_66', 'nagawara', 'Nagawara', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_67', 'nanavati-hospital', 'Nanavati Hospital', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_68', 'nayandahalli', 'Nayandahalli', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_69', 'nerul', 'Nerul', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_70', 'nibm-road', 'Nibm Road', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_71', 'panvel', 'Panvel', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_72', 'parbhani', 'Parbhani', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_73', 'poland', 'Poland', 'Europe', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_74', 'rajarajeshwari-nagar', 'Rajarajeshwari Nagar', 'India', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_75', 'ras-al-khor', 'Ras Al Khor', 'United Arab Emirates', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_76', 'ratnagiri', 'Ratnagiri', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_77', 'sampige-road', 'Sampige Road', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_78', 'sandal-soap-factory', 'Sandal Soap Factory', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_79', 'santa-cruz', 'Santa Cruz', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_80', 'santacruz', 'Santacruz', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_81', 'saraswat-nagar', 'Saraswat Nagar', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_82', 'satara', 'Satara', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_83', 'shivaji-chowk', 'Shivaji Chowk', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_84', 'siddharth-colony', 'Siddharth Colony', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_85', 'sindhudurg', 'Sindhudurg', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_86', 'singasandra', 'Singasandra', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_87', 'solapur', 'Solapur', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_88', 'srirampuram', 'Srirampuram', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_89', 'surya-nagar', 'Surya Nagar', 'Delhi-NCR', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_90', 'swami-samarth-nagar', 'Swami Samarth Nagar', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_91', 'swami-vivekananda', 'Swami Vivekananda', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_92', 'tavarekere-main-road-btm-layout', 'Tavarekere Main Road Btm Layout', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_93', 'trinity', 'Trinity', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_94', 'vidhana-soudha', 'Vidhana Soudha', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_95', 'vile-parle', 'Vile Parle', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_96', 'vivekananda-nagar-banashankari-3rd-stage', 'Vivekananda Nagar Banashankari 3rd Stage', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124170_97', 'wardha-road-nagpur', 'Wardha Road Nagpur', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_98', 'yavatmal', 'Yavatmal', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_99', 'yelachenahalli', 'Yelachenahalli', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_100', 'yeshwanthpur', 'Yeshwanthpur', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_101', 'acharya', 'Acharya', 'India', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_102', 'ahilyanagar', 'Ahilyanagar', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_103', 'ahmednagar', 'Ahmednagar', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_104', 'ajman', 'Ajman', 'United Arab Emirates', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_105', 'al-wajeha-al-bahriah', 'Al Wajeha Al Bahriah', 'United Arab Emirates', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_106', 'anand-nagar-dahisar', 'Anand Nagar Dahisar', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_107', 'bhandup-west', 'Bhandup West', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_108', 'bkc-mumbai', 'BKC Mumbai', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_109', 'bommanahalli', 'Bommanahalli', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_110', 'byappanahalli', 'Byappanahalli', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_111', 'challaghatta', 'Challaghatta', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_112', 'charkop', 'Charkop', 'India', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_113', 'cotton-green', 'Cotton Green', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_114', 'dadar', 'Dadar', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_115', 'dharampeth', 'Dharampeth', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_116', 'eksar', 'Eksar', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_117', 'garudacharpalya', 'Garudacharpalya', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_118', 'govandi', 'Govandi', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_119', 'hadaeq-mohammed-bin-rashid', 'Hadaeq Mohammed Bin Rashid', 'United Arab Emirates', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_120', 'hrbr-layout', 'HRBR Layout', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_121', 'iblur-village', 'Iblur Village', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_122', 'jakkur-layout', 'Jakkur Layout', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_123', 'jalna', 'Jalna', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_124', 'kadugondanahalli', 'Kadugondanahalli', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_125', 'kamraj-nagar', 'Kamraj Nagar', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_126', 'kanjurmarg-mumbai', 'Kanjurmarg Mumbai', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_127', 'majestic', 'Majestic', 'India', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_128', 'malad-west', 'Malad West', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_129', 'manewada', 'Manewada', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_130', 'marathahalli', 'Marathahalli', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_131', 'mira-road', 'Mira Road', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_132', 'nakhlat-deira', 'Nakhlat Deira', 'United Arab Emirates', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_133', 'nandurbar', 'Nandurbar', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_134', 'palghar', 'Palghar', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_135', 'pottery-town', 'Pottery Town', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_136', 'rajajinagar', 'Rajajinagar', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_137', 'rambaug-powai', 'Rambaug Powai', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_138', 'ras-al-khaimah', 'Ras Al Khaimah', 'United Arab Emirates', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_139', 'rashtriya-military-school', 'Rashtriya Military School', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_140', 'reay-road', 'Reay Road', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_141', 'seepz', 'SEEPZ Andheri', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_142', 'seethappa-layout', 'Seethappa Layout', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_143', 'shimpoli', 'Shimpoli', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_144', 'shitladevi', 'Shitladevi', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_145', 'swami-vivekananda-vidyashala-banashankari-1st-stage', 'Swami Vivekananda Vidyashala Banashankari 1st Stage', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_146', 'umm-al-quwain', 'Umm Al Quwain', 'United Arab Emirates', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_147', 'vashi', 'Vashi', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_148', 'vidyanagari', 'Vidyanagari', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_149', 'wardha', 'Wardha', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_150', 'worli', 'Worli', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_151', 'zabeel', 'Zabeel', 'United Arab Emirates', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_152', 'agrahara-dasarahalli', 'Agrahara Dasarahalli', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_153', 'al-awir', 'Al Awir', 'United Arab Emirates', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_154', 'aundh', 'Aundh', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_155', 'buldhana', 'Buldhana', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_156', 'central-college', 'Central College', 'India', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_157', 'chandrapur', 'Chandrapur', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_158', 'charni-road', 'Charni Road', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_159', 'chembur-east', 'Chembur East', 'India', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_160', 'don-bosco', 'Don Bosco', 'Delhi-NCR', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_161', 'girgaon-mumbai', 'Girgaon Mumbai', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_162', 'goregaon', 'Goregaon', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_163', 'hinjewadi', 'Hinjewadi', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_164', 'hsr-layout', 'HSR Layout', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_165', 'hulimavu', 'Hulimavu', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_166', 'iim-bangalore', 'IIM Bangalore', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_167', 'jalgaon', 'Jalgaon', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_168', 'jebel-ali', 'Jebel Ali', 'United Arab Emirates', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_169', 'jp-nagar', 'JP Nagar', 'India', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_170', 'jp-nagar-4th-phase', 'JP Nagar 4th Phase', 'India', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_171', 'jumeirah', 'Jumeirah', 'United Arab Emirates', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_172', 'kalbadevi', 'Kalbadevi', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_173', 'kalena-agrahara', 'Kalena Agrahara', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_174', 'karthik-nagar', 'Karthik Nagar', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_175', 'khira-nagar', 'Khira Nagar', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_176', 'kodigehalli', 'Kodigehalli', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_177', 'konappana-agrahara', 'Konappana Agrahara', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_178', 'kundalahalli', 'Kundalahalli', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_179', 'kurla', 'Kurla', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_180', 'langford-town', 'Langford Town', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_181', 'magadi-road', 'Magadi Road', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_182', 'mexico', 'Mexico', 'North America', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_183', 'pattanagere', 'Pattanagere', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_184', 'peenya', 'Peenya', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_185', 'powai-lake', 'Powai Lake', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_186', 'prabhadevi', 'Prabhadevi', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_187', 'pune', 'Pune', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_188', 'sandhurst-road', 'Sandhurst Road', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_189', 'shankar-nagar', 'Shankar Nagar', 'India', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_190', 'sharjah', 'Sharjah', 'United Arab Emirates', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_191', 'shri-satya-sai-hospital', 'Shri Satya Sai Hospital', 'India', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_192', 'siddhivinayak', 'Siddhivinayak', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_193', 'thalaghattapura', 'Thalaghattapura', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_194', 'vajarahalli', 'Vajarahalli', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_195', 'vijayanagar', 'Vijayanagar', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_196', 'benniganahalli-bangalore', 'Benniganahalli Bangalore', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_197', 'bommasandra', 'Bommasandra', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_198', 'dubai', 'Dubai', 'United Arab Emirates', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_199', 'hebbal', 'Hebbal', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_200', 'jnana-jyothi-nagar-jnana-bharathi', 'Jnana Jyothi Nagar Jnana Bharathi', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_201', 'kempapura', 'Kempapura', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_202', 'kolhapur', 'Kolhapur', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_203', 'koradi-road', 'Koradi Road', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_204', 'kr-puram', 'KR Puram', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_205', 'lalji-nagar-lakkasandra', 'Lalji Nagar Lakkasandra', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_206', 'mahalakshmi-layout', 'Mahalakshmi Layout', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_207', 'mankhurd', 'Mankhurd', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_208', 'marine-lines', 'Marine Lines', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_209', 'matunga-road', 'Matunga Road', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_210', 'nahur', 'Nahur', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_211', 'osmanabad', 'Osmanabad', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_212', 'rashtriya-vidyalaya', 'Rashtriya Vidyalaya', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_213', 'silk-board', 'Silk Board', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_214', 'sion', 'Sion', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_215', 'south-end-circle', 'South End Circle', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_216', 'tannery-road', 'Tannery Road', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_217', 'thane', 'Thane', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_218', 'unnao', 'Unnao', 'Uttar Pradesh', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_219', 'venkateshpura', 'Venkateshpura', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_220', 'vidhan-bhavan-nariman-point', 'Vidhan Bhavan Nariman Point', 'Maharashtra', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;
INSERT INTO `location` (`id`, `slug`, `name`, `region`, `isActive`, `createdAt`, `updatedAt`) VALUES ('loc_1790867124171_221', 'yelahanka', 'Yelahanka', 'Karnataka', 1, NOW(), NOW()) ON DUPLICATE KEY UPDATE `isActive` = 1;

-- 2. Link all Services with all Active Locations (Covers 100% GSC URLs)
INSERT INTO `servicelocation` (`id`, `serviceId`, `locationId`, `published`, `createdAt`, `updatedAt`)
SELECT 
  CONCAT('sl_', SUBSTRING(MD5(CONCAT(s.id, '_', l.id)), 1, 16)) AS `id`,
  s.id AS `serviceId`,
  l.id AS `locationId`,
  1 AS `published`,
  NOW() AS `createdAt`,
  NOW() AS `updatedAt`
FROM `service` s
CROSS JOIN `location` l
WHERE l.isActive = 1
ON DUPLICATE KEY UPDATE 
  `published` = 1;

-- 3. Compatibility Views for Linux MariaDB
CREATE OR REPLACE VIEW `Location` AS SELECT * FROM `location`;
CREATE OR REPLACE VIEW `ServiceLocation` AS SELECT * FROM `servicelocation`;
CREATE OR REPLACE VIEW `Service` AS SELECT * FROM `service`;
CREATE OR REPLACE VIEW `ServiceFaq` AS SELECT * FROM `servicefaq`;

SET FOREIGN_KEY_CHECKS = 1;

-- 4. Verification Check
SELECT 
  (SELECT COUNT(*) FROM `location`) AS `total_locations`,
  (SELECT COUNT(*) FROM `service`) AS `total_services`,
  (SELECT COUNT(*) FROM `servicelocation` WHERE `published` = 1) AS `total_live_service_locations`;
